var BusinessConstants = {
  BUSINESSES_RECEIVED: "BUSINESSES_RECEIVED",
  BUSINESS_RECEIVED: "BUSINESS_RECEIVED",
  ALL_BUSINESSES_RECEIVED: "ALL_BUSINESSES_RECEIVED",
  FIND_BUSINESS: "FIND_BUSINESS",
  PAGINATION_RECEIVED: "PAGINATION_RECEIVED"
};

module.exports = BusinessConstants;
