BusinessConstants = {
  BUSINESSES_RECEIVED: "BUSINESSES_RECEIVED",
  BUSINESS_RECEIVED: "BUSINESS_RECEIVED",
  ALL_BUSINESSES_RECEIVED: "ALL_BUSINESSES_RECEIVED"
};

module.exports = BusinessConstants
